import assert from "node:assert/strict";
import test from "node:test";
import {
  BINANCE_FUTURES_FIELDS,
  BINANCE_INTELLIGENCE,
  BINANCE_SPOT_FIELDS,
  CEX_VENUES,
} from "../services/cex-catalog.mjs";

test("the first ten centralized venues are the only live books", () => {
  assert.equal(CEX_VENUES.length, 15);
  const binance = CEX_VENUES[0];
  const bybit = CEX_VENUES[1];
  const okx = CEX_VENUES[2];
  const coinbase = CEX_VENUES[3];
  const kraken = CEX_VENUES[4];
  const kucoin = CEX_VENUES[5];
  const gate = CEX_VENUES[6];
  const bitget = CEX_VENUES[7];
  const mexc = CEX_VENUES[8];
  const htx = CEX_VENUES[9];
  assert.equal(binance.id, "binance");
  assert.equal(bybit.id, "bybit");
  assert.equal(bybit.spot.state, "live");
  assert.equal(bybit.futures.state, "live");
  assert.equal(bybit.spot.feed, "bybit-spot");
  assert.equal(bybit.futures.feed, "bybit-linear");
  assert.ok(bybit.spot.uses.every((place) => place.startsWith("Admin · Bybit")));
  assert.equal(bybit.spot.uses.some((place) => place.includes("Binance")), false);
  assert.equal(binance.spot.uses.some((place) => place.includes("Bybit")), false);
  assert.equal(okx.id, "okx");
  assert.equal(okx.spot.feed, "okx-spot");
  assert.equal(okx.futures.feed, "okx-swap");
  assert.equal(okx.spot.state, "live");
  assert.ok(okx.spot.uses.every((place) => place.startsWith("Admin · OKX")));
  assert.equal(okx.futures.uses.some((place) => place.includes("Binance")), false);
  assert.equal(coinbase.id, "coinbase");
  assert.equal(coinbase.spot.feed, "coinbase-spot");
  assert.equal(coinbase.futures.feed, "coinbase-futures");
  assert.equal(coinbase.spot.state, "live");
  assert.equal(coinbase.futures.state, "live");
  assert.ok(coinbase.spot.uses.every((place) => place.includes("Coinbase")));
  assert.equal(kraken.spot.feed, "kraken-spot");
  assert.equal(kraken.futures.feed, "kraken-futures");
  assert.equal(kucoin.spot.feed, "kucoin-spot");
  assert.equal(kucoin.futures.feed, "kucoin-futures");
  assert.equal(kraken.spot.uses.some((place) => place.includes("KuCoin")), false);
  assert.equal(kucoin.futures.uses.some((place) => place.includes("Kraken")), false);
  assert.equal(gate.spot.feed, "gate-spot");
  assert.equal(gate.futures.feed, "gate-futures");
  assert.equal(bitget.spot.feed, "bitget-spot");
  assert.equal(bitget.futures.feed, "bitget-futures");
  assert.equal(gate.spot.uses.some((place) => place.includes("Bitget")), false);
  assert.equal(mexc.spot.feed, "mexc-spot");
  assert.equal(mexc.futures.feed, "mexc-futures");
  assert.equal(htx.spot.feed, "htx-spot");
  assert.equal(htx.futures.feed, "htx-futures");
  assert.equal(mexc.spot.uses.some((place) => place.includes("HTX")), false);
  const bitfinex = CEX_VENUES.find((venue) => venue.id === "bitfinex");
  const bitstamp = CEX_VENUES.find((venue) => venue.id === "bitstamp");
  assert.equal(bitfinex?.spot.feed, "bitfinex-spot");
  assert.equal(bitfinex?.futures.feed, "bitfinex-futures");
  assert.equal(bitstamp?.spot.feed, "bitstamp-spot");
  assert.equal(bitstamp?.futures.feed, "bitstamp-futures");
  assert.equal(bitstamp?.futures.state, "live");
  assert.equal(bitfinex?.spot.uses.some((place) => place.includes("Bitstamp")), false);
  const crypto = CEX_VENUES.find((venue) => venue.id === "crypto-com");
  const upbit = CEX_VENUES.find((venue) => venue.id === "upbit");
  assert.equal(crypto?.spot.feed, "crypto-spot");
  assert.equal(crypto?.futures.feed, "crypto-futures");
  assert.equal(upbit?.spot.feed, "upbit-spot");
  assert.equal(upbit?.futures.state, "absent");
  assert.equal(upbit?.futures.uses.length, 0);
  const gemini = CEX_VENUES.find((venue) => venue.id === "gemini");
  assert.equal(gemini?.spot.feed, "gemini-spot");
  assert.equal(gemini?.futures.feed, "gemini-futures");
  assert.equal(gemini?.spot.uses.some((place) => place.includes("perpetual")), false);
  assert.equal(binance.id, "binance");
  assert.equal(binance.spot.state, "live");
  assert.equal(binance.futures.state, "live");
  assert.equal(binance.spot.feed, "binance-spot");
  assert.equal(binance.v3, undefined);
  assert.ok(binance.spot.uses.some((place) => place.includes("Spot API v3")));
  assert.equal(binance.futures.uses.some((place) => place.includes("Spot API v3")), false);
  assert.ok(binance.spot.uses.every((place) => place.startsWith("Market ·")));
  assert.ok(binance.futures.uses.some((place) => place.includes("funding")));
  assert.equal(binance.spot.uses.some((place) => place.includes("funding")), false);
  const closed = CEX_VENUES.filter((venue) => venue.spot.state !== "live");
  assert.equal(closed.length, 0);
  assert.equal(CEX_VENUES.filter((venue) => venue.futures.state !== "live").map((venue) => venue.id).join(","), "upbit");
  assert.equal(BINANCE_INTELLIGENCE.products.length, 3);
  assert.deepEqual(BINANCE_INTELLIGENCE.products.map((product) => product.id), ["binance-ai", "ai-pro", "agent-os"]);
  assert.ok(BINANCE_INTELLIGENCE.products.every((product) => product.state === "live" && product.address.includes("symbol=BTCUSDT") && product.uses.length === 1));
  assert.match(BINANCE_INTELLIGENCE.products[1].locked, /No order/);
  assert.match(BINANCE_INTELLIGENCE.products[2].locked, /not opened/);
  assert.ok(BINANCE_SPOT_FIELDS.some((field) => field.wasHidden && field.field === "t"));
  assert.ok(BINANCE_FUTURES_FIELDS.some((field) => field.wasHidden && field.field === "ap"));
});
