/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiViewStateRouteImport } from './routes/api/view-state'
import { Route as ApiDeskCsrfRouteImport } from './routes/api/desk/csrf'
import { Route as ApiDeskLoginRouteImport } from './routes/api/desk/login'
import { Route as ApiDeskLogoutRouteImport } from './routes/api/desk/logout'
import { Route as ApiDeskSessionRouteImport } from './routes/api/desk/session'
import { Route as ApiDexSearchRouteImport } from './routes/api/dex/search'
import { Route as ApiWalletsActivityRouteImport } from './routes/api/wallets/activity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiViewStateRoute = ApiViewStateRouteImport.update({
  id: '/api/view-state',
  path: '/api/view-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskCsrfRoute = ApiDeskCsrfRouteImport.update({
  id: '/api/desk/csrf',
  path: '/api/desk/csrf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskLoginRoute = ApiDeskLoginRouteImport.update({
  id: '/api/desk/login',
  path: '/api/desk/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskLogoutRoute = ApiDeskLogoutRouteImport.update({
  id: '/api/desk/logout',
  path: '/api/desk/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskSessionRoute = ApiDeskSessionRouteImport.update({
  id: '/api/desk/session',
  path: '/api/desk/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDexSearchRoute = ApiDexSearchRouteImport.update({
  id: '/api/dex/search',
  path: '/api/dex/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletsActivityRoute = ApiWalletsActivityRouteImport.update({
  id: '/api/wallets/activity',
  path: '/api/wallets/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/view-state': typeof ApiViewStateRoute
  '/api/desk/csrf': typeof ApiDeskCsrfRoute
  '/api/desk/login': typeof ApiDeskLoginRoute
  '/api/desk/logout': typeof ApiDeskLogoutRoute
  '/api/desk/session': typeof ApiDeskSessionRoute
  '/api/dex/search': typeof ApiDexSearchRoute
  '/api/wallets/activity': typeof ApiWalletsActivityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/view-state': typeof ApiViewStateRoute
  '/api/desk/csrf': typeof ApiDeskCsrfRoute
  '/api/desk/login': typeof ApiDeskLoginRoute
  '/api/desk/logout': typeof ApiDeskLogoutRoute
  '/api/desk/session': typeof ApiDeskSessionRoute
  '/api/dex/search': typeof ApiDexSearchRoute
  '/api/wallets/activity': typeof ApiWalletsActivityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/view-state': typeof ApiViewStateRoute
  '/api/desk/csrf': typeof ApiDeskCsrfRoute
  '/api/desk/login': typeof ApiDeskLoginRoute
  '/api/desk/logout': typeof ApiDeskLogoutRoute
  '/api/desk/session': typeof ApiDeskSessionRoute
  '/api/dex/search': typeof ApiDexSearchRoute
  '/api/wallets/activity': typeof ApiWalletsActivityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/view-state'
    | '/api/desk/csrf'
    | '/api/desk/login'
    | '/api/desk/logout'
    | '/api/desk/session'
    | '/api/dex/search'
    | '/api/wallets/activity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/view-state'
    | '/api/desk/csrf'
    | '/api/desk/login'
    | '/api/desk/logout'
    | '/api/desk/session'
    | '/api/dex/search'
    | '/api/wallets/activity'
  id:
    | '__root__'
    | '/'
    | '/api/view-state'
    | '/api/desk/csrf'
    | '/api/desk/login'
    | '/api/desk/logout'
    | '/api/desk/session'
    | '/api/dex/search'
    | '/api/wallets/activity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiViewStateRoute: typeof ApiViewStateRoute
  ApiDeskCsrfRoute: typeof ApiDeskCsrfRoute
  ApiDeskLoginRoute: typeof ApiDeskLoginRoute
  ApiDeskLogoutRoute: typeof ApiDeskLogoutRoute
  ApiDeskSessionRoute: typeof ApiDeskSessionRoute
  ApiDexSearchRoute: typeof ApiDexSearchRoute
  ApiWalletsActivityRoute: typeof ApiWalletsActivityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/view-state': {
      id: '/api/view-state'
      path: '/api/view-state'
      fullPath: '/api/view-state'
      preLoaderRoute: typeof ApiViewStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk/csrf': {
      id: '/api/desk/csrf'
      path: '/api/desk/csrf'
      fullPath: '/api/desk/csrf'
      preLoaderRoute: typeof ApiDeskCsrfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk/login': {
      id: '/api/desk/login'
      path: '/api/desk/login'
      fullPath: '/api/desk/login'
      preLoaderRoute: typeof ApiDeskLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk/logout': {
      id: '/api/desk/logout'
      path: '/api/desk/logout'
      fullPath: '/api/desk/logout'
      preLoaderRoute: typeof ApiDeskLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk/session': {
      id: '/api/desk/session'
      path: '/api/desk/session'
      fullPath: '/api/desk/session'
      preLoaderRoute: typeof ApiDeskSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dex/search': {
      id: '/api/dex/search'
      path: '/api/dex/search'
      fullPath: '/api/dex/search'
      preLoaderRoute: typeof ApiDexSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallets/activity': {
      id: '/api/wallets/activity'
      path: '/api/wallets/activity'
      fullPath: '/api/wallets/activity'
      preLoaderRoute: typeof ApiWalletsActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiViewStateRoute: ApiViewStateRoute,
  ApiDeskCsrfRoute: ApiDeskCsrfRoute,
  ApiDeskLoginRoute: ApiDeskLoginRoute,
  ApiDeskLogoutRoute: ApiDeskLogoutRoute,
  ApiDeskSessionRoute: ApiDeskSessionRoute,
  ApiDexSearchRoute: ApiDexSearchRoute,
  ApiWalletsActivityRoute: ApiWalletsActivityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
